'use client';

import { useState, useCallback } from 'react';
import { FileExplorer } from './FileExplorer';
import { CollaborativeMonacoEditor } from './CollaborativeMonacoEditor';
import { FileNode } from '@/types/collaboration';
import { Terminal, Code, Database, Globe, Settings } from 'lucide-react';

interface EditorWorkspaceProps {
  sessionId: string;
  projectId: string;
  initialFiles?: FileNode[];
  className?: string;
}

const DEFAULT_FILES: FileNode[] = [
  {
    id: '1',
    name: 'src',
    path: '/src',
    type: 'directory',
    children: [
      {
        id: '2',
        name: 'App.tsx',
        path: '/src/App.tsx',
        type: 'file',
        language: 'typescript',
        content: `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to FlareForge AI Studio</h1>
        <p>Your AI-powered development environment</p>
      </header>
    </div>
  );
}

export default App;`,
      },
      {
        id: '3',
        name: 'index.ts',
        path: '/src/index.ts',
        type: 'file',
        language: 'typescript',
        content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
      },
    ],
  },
  {
    id: '4',
    name: 'package.json',
    path: '/package.json',
    type: 'file',
    language: 'json',
    content: `{
  "name": "flareforge-project",
  "version": "0.1.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}`,
  },
  {
    id: '5',
    name: 'README.md',
    path: '/README.md',
    type: 'file',
    language: 'markdown',
    content: `# FlareForge AI Project

This project was generated by FlareForge AI Studio.

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Start development server:
\`\`\`bash
npm run dev
\`\`\`

## Features

- AI-powered code generation
- Real-time collaboration
- 3D visualization
- Advanced debugging tools`,
  },
];

export function EditorWorkspace({ sessionId, projectId, initialFiles = DEFAULT_FILES, className = '' }: EditorWorkspaceProps) {
  const [files, setFiles] = useState<FileNode[]>(initialFiles);
  const [selectedFile, setSelectedFile] = useState<string>('/src/App.tsx');
  const [activeTab, setActiveTab] = useState<'editor' | 'terminal' | 'database' | 'preview'>('editor');
  const [terminalOpen, setTerminalOpen] = useState(false);
  const [sidebarWidth, setSidebarWidth] = useState(240);

  const selectedFileNode = findFileNode(files, selectedFile);

  const handleFileSelect = useCallback((filePath: string) => {
    setSelectedFile(filePath);
  }, []);

  const handleFileCreate = useCallback((parentPath: string, name: string, type: 'file' | 'directory') => {
    const newPath = parentPath === '/' ? `/${name}` : `${parentPath}/${name}`;

    if (type === 'file') {
      const newFile: FileNode = {
        id: Date.now().toString(),
        name,
        path: newPath,
        type: 'file',
        language: getFileLanguage(name),
        content: '',
      };

      addFileToTree(files, parentPath, newFile);
    } else {
      const newDir: FileNode = {
        id: Date.now().toString(),
        name,
        path: newPath,
        type: 'directory',
        children: [],
      };

      addFileToTree(files, parentPath, newDir);
    }

    setFiles([...files]);
  }, [files]);

  const handleFileDelete = useCallback((filePath: string) => {
    removeFileFromTree(files, filePath);
    setFiles([...files]);

    if (selectedFile === filePath) {
      setSelectedFile('/src/App.tsx');
    }
  }, [files, selectedFile]);

  const handleFileRename = useCallback((filePath: string, newName: string) => {
    renameFileInTree(files, filePath, newName);
    setFiles([...files]);

    if (selectedFile === filePath) {
      const newPath = filePath.replace(/[^/]+$/, newName);
      setSelectedFile(newPath);
    }
  }, [files, selectedFile]);

  return (
    <div className={`flex h-full bg-gray-900 text-white ${className}`}>
      {/* Sidebar - File Explorer */}
      <div
        className="bg-gray-800 border-r border-gray-700 flex flex-col"
        style={{ width: `${sidebarWidth}px` }}
      >
        <div className="flex-1 overflow-hidden">
          <FileExplorer
            files={files}
            selectedFile={selectedFile}
            onFileSelect={handleFileSelect}
            onFileCreate={handleFileCreate}
            onFileDelete={handleFileDelete}
            onFileRename={handleFileRename}
            className="h-full"
          />
        </div>

        {/* Bottom Toolbar */}
        <div className="border-t border-gray-700 p-2">
          <div className="grid grid-cols-2 gap-1">
            <button
              onClick={() => setActiveTab('terminal')}
              className={`p-2 rounded transition-colors ${
                activeTab === 'terminal' ? 'bg-gray-700' : 'hover:bg-gray-700'
              }`}
              title="Terminal"
            >
              <Terminal className="h-4 w-4" />
            </button>
            <button
              onClick={() => setActiveTab('database')}
              className={`p-2 rounded transition-colors ${
                activeTab === 'database' ? 'bg-gray-700' : 'hover:bg-gray-700'
              }`}
              title="Database"
            >
              <Database className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Resize Handle */}
      <div
        className="w-1 bg-gray-700 hover:bg-purple-600 cursor-col-resize transition-colors"
        onMouseDown={(e) => {
          const startX = e.clientX;
          const startWidth = sidebarWidth;

          const handleMouseMove = (e: MouseEvent) => {
            const newWidth = startWidth + (e.clientX - startX);
            setSidebarWidth(Math.max(150, Math.min(400, newWidth)));
          };

          const handleMouseUp = () => {
            document.removeEventListener('mousemove', handleMouseMove);
            document.removeEventListener('mouseup', handleMouseUp);
          };

          document.addEventListener('mousemove', handleMouseMove);
          document.addEventListener('mouseup', handleMouseUp);
        }}
      />

      {/* Main Editor Area */}
      <div className="flex-1 flex flex-col">
        {/* Tabs */}
        <div className="bg-gray-800 border-b border-gray-700">
          <div className="flex items-center">
            <button
              onClick={() => setActiveTab('editor')}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                activeTab === 'editor'
                  ? 'bg-gray-900 text-white border-b-2 border-purple-500'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              <Code className="inline h-4 w-4 mr-2" />
              Editor
            </button>
            <button
              onClick={() => setActiveTab('preview')}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                activeTab === 'preview'
                  ? 'bg-gray-900 text-white border-b-2 border-purple-500'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              <Globe className="inline h-4 w-4 mr-2" />
              Preview
            </button>
            <button
              onClick={() => setActiveTab('terminal')}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                activeTab === 'terminal'
                  ? 'bg-gray-900 text-white border-b-2 border-purple-500'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              <Terminal className="inline h-4 w-4 mr-2" />
              Terminal
            </button>
            <button
              onClick={() => setActiveTab('database')}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                activeTab === 'database'
                  ? 'bg-gray-900 text-white border-b-2 border-purple-500'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              <Database className="inline h-4 w-4 mr-2" />
              Database
            </button>
          </div>
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-hidden">
          {activeTab === 'editor' && selectedFileNode && (
            <CollaborativeMonacoEditor
              sessionId={sessionId}
              filePath={selectedFileNode.path}
              initialContent={selectedFileNode.content || ''}
              language={selectedFileNode.language || 'plaintext'}
              onContentChange={(content) => {
                // Update file content in tree
                updateFileContent(files, selectedFileNode.path, content);
              }}
            />
          )}

          {activeTab === 'preview' && (
            <div className="h-full flex items-center justify-center text-gray-500">
              <div className="text-center">
                <Globe className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>Live Preview</p>
                <p className="text-sm mt-2">Preview your application here</p>
              </div>
            </div>
          )}

          {activeTab === 'terminal' && (
            <div className="h-full bg-black p-4 font-mono text-sm">
              <div className="text-green-400">$ Welcome to FlareForge Terminal</div>
              <div className="text-gray-400 mt-2">Type commands to interact with your project...</div>
              <div className="flex items-center mt-4">
                <span className="text-green-400">$</span>
                <input
                  type="text"
                  className="bg-transparent outline-none ml-2 flex-1"
                  placeholder="Enter command..."
                />
              </div>
            </div>
          )}

          {activeTab === 'database' && (
            <div className="h-full flex items-center justify-center text-gray-500">
              <div className="text-center">
                <Database className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>Database Manager</p>
                <p className="text-sm mt-2">Visual database tools coming soon</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// Helper functions for file tree manipulation
function findFileNode(files: FileNode[], path: string): FileNode | undefined {
  for (const file of files) {
    if (file.path === path) return file;
    if (file.children) {
      const found = findFileNode(file.children, path);
      if (found) return found;
    }
  }
  return undefined;
}

function addFileToTree(files: FileNode[], parentPath: string, newFile: FileNode): void {
  for (const file of files) {
    if (file.path === parentPath && file.type === 'directory') {
      if (!file.children) file.children = [];
      file.children.push(newFile);
      return;
    }
    if (file.children) {
      addFileToTree(file.children, parentPath, newFile);
    }
  }
}

function removeFileFromTree(files: FileNode[], path: string): boolean {
  for (let i = 0; i < files.length; i++) {
    if (files[i].path === path) {
      files.splice(i, 1);
      return true;
    }
    if (files[i].children) {
      if (removeFileFromTree(files[i].children!, path)) return true;
    }
  }
  return false;
}

function renameFileInTree(files: FileNode[], oldPath: string, newName: string): boolean {
  for (const file of files) {
    if (file.path === oldPath) {
      file.name = newName;
      file.path = file.path.replace(/[^/]+$/, newName);
      if (file.children) {
        file.children.forEach(child => {
          child.path = file.path + child.path.replace(oldPath, '');
        });
      }
      return true;
    }
    if (file.children) {
      if (renameFileInTree(file.children, oldPath, newName)) return true;
    }
  }
  return false;
}

function updateFileContent(files: FileNode[], path: string, content: string): void {
  for (const file of files) {
    if (file.path === path) {
      file.content = content;
      return;
    }
    if (file.children) {
      updateFileContent(file.children, path, content);
    }
  }
}

function getFileLanguage(fileName: string): string {
  const ext = fileName.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'ts':
    case 'tsx':
      return 'typescript';
    case 'js':
    case 'jsx':
      return 'javascript';
    case 'css':
      return 'css';
    case 'html':
      return 'html';
    case 'json':
      return 'json';
    case 'md':
      return 'markdown';
    case 'py':
      return 'python';
    case 'sql':
      return 'sql';
    default:
      return 'plaintext';
  }
}